Fix missing uri require in rake openapi:generate
Fixes:
```
rake aborted!
NoMethodError: undefined method `URI' for main (NoMethodError)

      uri          = URI("https://cloud.ibm.com/apidocs/#{openapi_json}")

```